### ISSUE TITLE
KickStarter 源码编译问题

### ISSUE THREAD

**Issue by Anderson-Hyl** [Lebron1992/learning-notes#1]
大佬，您的源码分析真棒，跟着一步一步读下去，复杂的代码清晰多了。但我碰到一个问题，这个 kickstarter 的源码我始终编译不过，想问一下您那边有没有已经编译好的工程文件呢？

**Comment by Lebron1992** [comment]
@AtmanChen  这个编译成功是有点麻烦，我当时第一次 clone 下来也搞了好久。你根据它的步骤来看下看看，有问题把错误贴上来。

**Comment by Anderson-Hyl** [comment]
嗯，我正在试，好像是有一个 framework 用的 Swift 5.2 编译的，然后现在正在用的 Xcode 是 11.4.1 里面是 Swift 5.2.2 ，运行 Carthage 会有个 “Incompatible Swift version - framework was built with 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29) and the local version is 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)”。我试试其他 Xcode 版本
